spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_jpa
    username: admin
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQL95Dialect